// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reply.ContactManagement.Db;

#nullable disable

namespace Reply.ContactManagement.Db.Migrations
{
    [DbContext(typeof(ContactManagementDbContext))]
    partial class ContactManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reply.ContactManagement.Core.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("Contacts", (string)null);
                });

            modelBuilder.Entity("Reply.ContactManagement.Core.Entities.ContactCustomFieldValue", b =>
                {
                    b.Property<Guid>("ContactId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomFieldId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("bit");

                    b.Property<int?>("IntegerValue")
                        .HasColumnType("int");

                    b.Property<string>("StringValue")
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId", "CustomFieldId");

                    b.HasIndex("CustomFieldId");

                    b.ToTable("ContactCustomFieldValues", (string)null);
                });

            modelBuilder.Entity("Reply.ContactManagement.Core.Entities.CustomField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CustomFields", (string)null);
                });

            modelBuilder.Entity("Reply.ContactManagement.Core.Entities.ContactCustomFieldValue", b =>
                {
                    b.HasOne("Reply.ContactManagement.Core.Entities.Contact", "Contact")
                        .WithMany("CustomFieldValues")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reply.ContactManagement.Core.Entities.CustomField", "CustomField")
                        .WithMany("ContactValues")
                        .HasForeignKey("CustomFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("CustomField");
                });

            modelBuilder.Entity("Reply.ContactManagement.Core.Entities.Contact", b =>
                {
                    b.Navigation("CustomFieldValues");
                });

            modelBuilder.Entity("Reply.ContactManagement.Core.Entities.CustomField", b =>
                {
                    b.Navigation("ContactValues");
                });
#pragma warning restore 612, 618
        }
    }
}
